---
- name: Add yunion rpm repository
  get_url:
    url: https://iso.yunion.cn/yumrepo-3.8/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_centos_x86 is defined

- name: Install yunion common packages
  yum:
    state: latest
    enablerepo: "yunion*"
    disablerepo: "*"
    name:
      - kernel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-devel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-headers-3.10.0-1160.6.1.el7.yn20201125
      - yunion-executor
  when:
  - is_centos_x86 is defined
  - non_iso_mode is defined

- name: init apt cache for debian
  get_url:
    url: https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.8/yunion.gpg-key.asc
    dest: /tmp/yunion.gpg-key.asc
    validate_certs: no
  become: yes
  when:
  - is_debian_based is defined

- name: apply debian sig key
  shell: |
    apt-key add /tmp/yunion.gpg-key.asc;
    apt-get update -y;
    rm -f /tmp/yunion.gpg-key.asc
  args:
    executable: /bin/bash
  when:
  - is_debian_based is defined
