- name: Online pacman repo
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [yunion]
      SigLevel = Optional TrustAll
      Server = https://iso.yunion.cn/archlinux/$repo/$arch/
    marker: "# {mark} ANSIBLE MANAGED BLOCK - yunion repo"
    insertafter: EOF
    create: true
    mode: '0600'
  become: yes
  when:
  - online_status is defined
  - online_status == 'online'

- name: ensure pacman repo synchronized
  shell: |
    pacman -Syy
  become: true

- name: Install Common Packages
  include_role:
    name: utils/install_packages
    apply:
      tags:
      - package
  vars:
    packages_to_install: "{{ common_packages }}"
  when: common_packages is defined
  tags:
  - package

- name: Install Latest Packages {{ onecloud_version_abbr | default('') }}
  include_role:
    name: utils/install_packages
    apply:
      tags:
      - package
  vars:
    packages_to_install: "{{ latest_packages }}"
    package_state: latest
    package_ignore_errors: true
    package_retries: 6
    package_delay: 10
  when: latest_packages is defined
  tags:
  - package
