---
- name: Make Cache
  shell: |
    yum clean all
    yum -y --disablerepo='*' --enablerepo='yunion*' makecache
  become: yes
  when:
  - is_centos_based is defined

- name: Append Packages To Common Packages
  set_fact:
    common_packages: "{{ common_packages + extra_packages }}"
  when:
  - extra_packages is defined
  - common_packages is defined

- name: Install Common Packages Via Loop
  package:
    name: "{{ package_item }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  retries: 3
  delay: 3
  with_items:
  - "{{ common_packages }}"
  loop_control:
    index_var: item_index
    label: "[{{ '%02d'|format(item_index + 1) }}/{{ common_packages|length }}] {{ package_item }}"
    loop_var: package_item
  become: yes
  tags:
  - package

- name: Install Latest Packages Via Loop {{ onecloud_version_abbr }}
  package:
    name: "{{ package_item }}"
    state: latest
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  with_items:
  - "{{ latest_packages }}"
  become: yes
  retries: 6
  delay: 10
  register: latest_pkg_result
  until: latest_pkg_result.rc == 0
  ignore_errors: yes
  when:
  - latest_packages is defined
  loop_control:
    index_var: item_index
    label: "[{{ item_index + 1 }}/{{ latest_packages | length }}] {{ package_item | regex_replace('\\[.*|[*]', '') }}"
    loop_var: package_item
  tags:
  - package

- name: Selinux Status
  shell: |
    sestatus |grep '^SELinux status:' |awk '{print $3}'
  register: selinux_status
  ignore_errors: yes

- name: Check That If Selinux Config Exists
  stat:
    path: /etc/selinux/config
  register: selinux_conf_exists

- name: Turn off selinux
  selinux:
    state: disabled
  become: yes
  when:
    - selinux_status.stdout | default("") != "disabled"
    - selinux_conf_exists.stat.exists
