---
- block:
  - name: Write /etc/systemd/resolved.conf
    become: true
    template:
      src: etc_systemd_resolved.conf.j2
      dest: /etc/systemd/resolved.conf
      owner: root
      group: root
      mode: 0644

  - name: Restart systemd-resolved
    become: true
    service:
      name: systemd-resolved
      state: restarted

  - name: Link /etc/resolv.conf to /run/systemd/resolve/resolve.conf
    become: true
    shell: |
      ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
    args:
      executable: /bin/bash

- name: Include Debian Family Common Tasks
  include_tasks: debian_family.yml
