---
- name: Import task utils/config_iptables.yml
  include_tasks: utils/config_iptables.yml

- name: set var
  set_fact:
    fou_url_base: "https://iso.yunion.cn/uos/{{ ansible_distribution_release }}/{{ onecloud_version_abbr }}/{{ ansible_architecture }}"

- name: init apt cache for UOS FOU
  get_url:
    url: "{{fou_url_base}}/yunion.gpg-key.asc"
    dest: /tmp/yunion.gpg-key.asc
    validate_certs: no
  become: true

- name: apply UOS FOU Sig key
  shell: |
    echo "deb [trusted=yes] {{fou_url_base}}/ ./" > /etc/apt/sources.list.d/yunion.list;
    apt-key add /tmp/yunion.gpg-key.asc;
    apt-get update -y;
    rm -f /tmp/yunion.gpg-key.asc
  become: true
  args:
    executable: /bin/bash

- name: Install common packages
  include_role:
    name: utils/install_packages
    apply:
      tags:
      - package
  vars:
    packages_to_install: "{{ common_packages }}"
  when: common_packages is defined
  tags:
  - package

- name: Install latest packages
  include_role:
    name: utils/install_packages
    apply:
      tags:
      - package
  vars:
    packages_to_install: "{{ latest_packages }}"
    package_state: latest
    package_ignore_errors: true
    package_retries: 6
    package_delay: 10
  when: latest_packages is defined
  tags:
  - package

- name: Check that if selinux config exists
  stat:
    path: /etc/selinux/config
  register: selinux_conf_exists

- name: Turn off selinux
  selinux:
    state: disabled
  become: true
  when:
    - selinux_conf_exists.stat.exists

- name: Import task utils/fix_ovmf_path
  include_tasks: utils/fix_ovmf_path.yml

# use legacy DNS resolve way
- block:
  - name: Write /etc/systemd/resolved.conf
    become: true
    template:
      src: etc_systemd_resolved.conf.j2
      dest: /etc/systemd/resolved.conf
      owner: root
      group: root
      mode: 0644

  - name: Restart systemd-resolved
    become: true
    service:
      name: systemd-resolved
      state: restarted

  - name: Link /etc/resolv.conf to /run/systemd/resolve/resolve.conf
    become: true
    shell: |
      ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
    args:
      executable: /bin/bash
