- name: Get Current Version
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    set -x
    OCVER=$(kubectl -n onecloud get onecloudclusters default -o=jsonpath='{.spec.version}')
    nslist="$(kubectl get namespace | tail -n +2 | awk '{print $1}' | xargs)"
    namespace=onecloud
    typ=deployment
    kubectl get $typ -n $namespace -o jsonpath='{range .items[*]}{@.metadata.name}{"@"}{@.spec.template.spec.containers[*].name}{"%"}{@.spec.template.spec.containers[*].image}{"\n"}{end}'} | while read line; do
      dep=$(echo $line | awk -F@ '{print $1}')
      names=($(echo $line | sed -e 's#.*@##g' -e 's#%.*$##g'))
      images=($(echo $line | sed -e 's#.*%##'))
      for idx in ${!names[@]}; do
        if ! echo "${images[$idx]}" | grep -Pq ":$OCVER\b"; then
          continue
        fi
            echo -e "kubectl set image -n $namespace $typ/$dep \c"
        echo -e "${names[$idx]}=${images[$idx]} \c"
      done
      echo
    done | sort -u | sed -e '/^$/d' -e 's#^  *##' -e 's#  *$##'
    kubectl get $typ -n $namespace -o jsonpath='{range .items[*]}{@.metadata.name}{"@"}{@.spec.template.spec.initContainers[*].name}{"%"}{@.spec.template.spec.initContainers[*].image}{"\n"}{end}'} | while read line; do
      if ! echo "$line" | grep -q '@%$'; then
        dep=$(echo $line | awk -F@ '{print $1}')
        img=$(echo "$line" | sed -e 's#.*%##')
        if ! echo "${images[$idx]}" | grep -Pq ":$OCVER\b"; then
          continue
        fi
        echo -e "kubectl set image -n $namespace $typ/$dep \c"
        echo -e "init=$img \c"
      fi
      echo
    done | sed -e 's# kubectl#\nkubectl#g' |sort -u | sed -e '/^$/d' -e 's#^  *##' -e 's#  *$##'
  args:
    executable: /bin/bash
  register: oc_deployment_images

- name: Parse image names from lines
  set_fact:
    image_names: "{{ image_names|default([]) + [item.split('=')[-1]] }}"
  loop: "{{ oc_deployment_images.stdout_lines }}"

- name: Pull Docker images
  command: "docker pull {{ image_item }}"
  loop: "{{ image_names }}"
  loop_control:
    index_var: item_index
    label: "[{{ '%02d'|format(item_index + 1) }}/{{ image_names|length }}] {{ image_item }}"
    loop_var: image_item

- shell: exit 1