- name: Enable and start yunion-containerd service
  ansible.builtin.systemd:
    name: yunion-containerd
    enabled: yes
    state: started

- name: Check crictl version
  shell: |
    crictl -r unix:///var/run/onecloud/containerd/containerd.sock version
    crictl -r unix:///var/run/onecloud/containerd/containerd.sock pods
  register: crictl_version
  changed_when: false

- debug: var=crictl_version.stdout_lines
