---
- name: Setup repo mirrors
  include_role:
    name: utils/mirror
  when:
  - is_centos | default(false) | bool == true

- name: sync files
  synchronize:
    src:  "{{ item }}"
    dest: "{{ item }}"
    delete: yes
    recursive: yes
  delegate_to: "{{ primary_node_ip }}"
  with_items:
    - /etc/yum.repos.d/yunion.repo
    - "{{ offline_data_path }}/repodata/"
    - "{{ offline_data_path }}/rpms/"
  when:
  - primary_node_ip is defined
  - primary_node_ip != ansible_default_ipv4.address
