is_arch_based: true
is_arch_based_aarch64: true
arch_based_arch: arm64

common_packages:
  - bash-completion
  - bridge-utils
  - conntrack-tools
  - cron
  - curl
  - dkms
  - ipset
  - ipvsadm
  - jq
  - nfs-utils
  - chrony
  - parallel
  - rsync
  - pciutils
  - tcpdump
  - python-selinux
  - python-setuptools
  - python-pip
  - "{{ yunion_qemu_package }}"
  - yunion-executor
  - yunion-ovmfrpm

common_services:
  - yunion-executor
