---
is_redhat_based: true
is_centos_based: true
is_centos_aarch64: true
is_centos: true
centos_version: 8

preinstall_packages:
    - epel-release
    - centos-release-nfv-openvswitch
    - centos-release-ceph-reef

common_packages:
    - bash-completion
    - bridge-utils
    - ceph-common
    - conntrack-tools
    - curl
    - fuse
    - jq
    - kmod
    - nfs-utils
    - openvswitch2.15
    - parallel
    - rsync
    - tcpdump
    - python3-libselinux
    - python3-pip
    - "{{ yunion_qemu_package }}"

k8s_packages:
    - container-selinux
    - containerd.io
    - cri-tools
    - docker-ce
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni

common_services:
    - chrony
    - yunion-executor