is_debian_based: true
is_debian_based_x86: true
debian_based_arch: amd64

common_packages:
  - apt-transport-https
  - bash-completion
  - bridge-utils
  - ceph-common
  - conntrack
  - conntrackd
  - cron
  - curl
  - dkms
  - gnupg-agent
  - gnupg2
  - ipset
  - ipvsadm
  - jq
  - nfs-common
  - chrony
  - openvswitch-switch
  - ovmf
  - parallel
  - python3-selinux
  - python3-setuptools
  - "{{ yunion_qemu_package }}"
  - yunion-executor

common_services:
    - ntp
    - yunion-executor

debian_latest_version_tag: "{% if onecloud_version | regex_search('^master') %}20{% else %}{{ onecloud_version | regex_replace('[^0-9.]+') | regex_findall('^[0-9]+\\.[0-9]+') | join('') }}{% endif %}"

latest_packages:
    - ca-certificates
    - "yunion-climc={{ debian_latest_version_tag }}*"
    - "yunion-climc-ee={{ debian_latest_version_tag }}*"

k8s_packages:
    - docker-ce
    - kubeadm=1.15.12-00
    - kubectl=1.15.12-00
    - kubelet=1.15.12-00
