---

is_redhat_based: true
is_kylin_x86: true
is_kylin_based: true
is_centos_based: true

common_packages:
  - bash-completion
  - bridge-utils
  - ceph-common
  - conntrack-tools
  - curl
  - fuse
  - jq
  - kmod
  - nfs-utils
  - openvswitch
  - parallel
  - rsync
  - tcpdump
  - python3-libselinux
  - "{{ yunion_qemu_package }}"

common_services:
  - ntpd
  - yunion-executor

k8s_packages:
    - containerd.io
    - cri-tools
    - docker-ce
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni
