---
is_redhat_based: true
is_centos_based: true
is_centos_x86: true

preinstall_packages:
    - epel-release

imported_repos:
    - https://mirror.stream.centos.org/SIGs/8/storage/{{ ansible_architecture }}/ceph-pacific/

common_packages:
    - bash-completion
    - bridge-utils
    - ceph-common
    - chrony
    - conntrack-tools
    - curl
    - fuse
    - jq
    - kmod
    - lvm2
    - nfs-utils
    - openvswitch
    - parallel
    - rsync
    - pciutils
    - tcpdump
    - python3-libselinux
    - python3-pip
    - "{{ yunion_qemu_package }}"

common_services:
    - chronyd
    - yunion-executor

k8s_packages:
    - container-selinux
    - containerd.io
    - cri-tools
    - docker-ce
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni