is_debian_based: true
is_ubuntu_based: true
is_ubuntu_based_x86: true
debian_based_arch: amd64

common_packages:
  - apt-transport-https
  - bash-completion
  - bridge-utils
  - ceph-common
  - conntrack
  - conntrackd
  - cron
  - curl
  - dkms
  - gnupg-agent
  - gnupg2
  - ipset
  - ipvsadm
  - jq
  - nfs-common
  - chrony
  - openvswitch-switch
  - ovmf
  - parallel
  - python3-selinux
  - software-properties-common
  - "{{ yunion_qemu_package }}"

common_services:
    - chrony
    - yunion-executor

latest_packages:
    - "yunion-climc={{ onecloud_version_abbr }}*"
    - "yunion-climc-ee={{ onecloud_version_abbr }}*"
    - ca-certificates
    - yunion-executor
    - yunion-fetcherfs

k8s_packages:
    - docker-ce
    - kubeadm=1.15.12-00
    - kubectl=1.15.12-00
    - kubelet=1.15.12-00
