- hosts: all
  roles:
    - utils/detect-os
    - common

- hosts: all
  roles:
    - utils/misc-check

- hosts: mariadb_node
  roles:
    - mariadb

- hosts: registry_node
  roles:
    - registry

- hosts: primary_master_node
  roles:
    - primary-master-node/setup_k8s
    - restore/add-sync-user

- hosts: primary_master_node
  roles:
    - primary-master-node/rsync_rpms

- hosts: master_nodes
  roles:
    - master-node

- hosts: worker_nodes
  roles:
    - worker-node

- hosts: primary_master_node:master_nodes:worker_nodes
  roles:
    - utils/gpu-init

- hosts: master_nodes:worker_nodes
  roles:
    - utils/kernel-check

- hosts: primary_master_node
  roles:
    - primary-master-node/setup_cloud
    - utils/enable-eip

- hosts: worker_nodes
  roles:
    - utils/eip-ha

- hosts: primary_master_node
  roles:
    - primary-master-node/reboot
